# Generated by Django 4.0.5 on 2022-06-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_alter_transactions_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
