# Generated by Django 4.0.5 on 2022-06-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_alter_transactions_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='reason',
            field=models.CharField(max_length=255),
        ),
    ]
